from pathlib import Path

import pytest

from backend.build_meta import APP_BUILD_ID


pytestmark = pytest.mark.no_db


BACKEND = Path(__file__).resolve().parents[1]
REPO_ROOT = BACKEND.parent


def test_monolithic_generators_use_selected_circuit_template():
    html = (BACKEND / "MetalFlowPro_v3_1.html").read_text(encoding="utf-8")

    assert "function mbSelectedTemplateQuery()" in html
    assert "mbAutoGenerateUrl()" in html
    assert "merAutoGenerateUrl()" in html
    assert "mass-balance-v2/auto-generate${mbSelectedTemplateQuery()}" in html
    assert "equipment-v2/auto-generate${mbSelectedTemplateQuery()}" in html


def test_backend_generation_routes_accept_selected_template_id():
    mb_source = (BACKEND / "routes" / "massbalance_v2.py").read_text(encoding="utf-8")
    mer_source = (BACKEND / "routes" / "equipment_v2.py").read_text(encoding="utf-8")

    assert "template_id: str | None = None" in mb_source
    assert "WHERE id = %s AND project_id = %s AND is_active = TRUE" in mb_source
    assert "template_id: str | None = None" in mer_source
    assert "WHERE id = %s AND project_id = %s AND is_active = TRUE" in mer_source


def test_design_criteria_surfaces_general_tables_before_equipment_parameters():
    html = (BACKEND / "MetalFlowPro_v3_1.html").read_text(encoding="utf-8")

    assert html.index("Critères généraux du projet") < html.index("${generalHtml}")
    assert html.index("${generalHtml}") < html.index("Paramètres des équipements sélectionnés")
    assert html.index("Paramètres des équipements sélectionnés") < html.index("${missingCriteriaNotice ||")
    assert "Paramètres équipements non chargés" in html
    assert "const groupsForTables = activeGroups;" in html
    assert '<span>Crit\\u00e8res de conception</span>' not in html
    assert APP_BUILD_ID in html
    assert "8 etapes lineaires" not in html
    assert "Phase selector bar" not in html
    assert "Zone de danger" not in html


def test_mass_balance_summary_exposes_frontend_recovery_alias():
    source = (BACKEND / "routes" / "massbalance_v2.py").read_text(encoding="utf-8")

    assert '"recovery_pct": round(recovery_pct, 2)' in source
    assert '"overall_recovery_pct": round(recovery_pct, 2)' in source
    # Throughput uses project target_tph when set, else inferred feed rate
    assert '"nominal_tph": round(float(proj.get("target_tph") or feed_tph), 1)' in source


def test_simulation_uses_equipment_v2_register():
    html = (BACKEND / "MetalFlowPro_v3_1.html").read_text(encoding="utf-8")

    assert "api('GET', `/projects/${S.pid}/equipment-v2`)" in html
    assert "loadEquipmentV2" in html
    assert "row['equipment_name']" in html or "equipment_name" in html
    assert "row['eq_type']" in html or "eq_type" in html
    assert "/simulation/params" in html


def test_mass_balance_regenerates_when_selected_circuit_is_partial_or_stale():
    html = (BACKEND / "MetalFlowPro_v3_1.html").read_text(encoding="utf-8")

    assert "function mbEnsureCircuitLoaded()" in html
    assert "function mbSelectedOpsSignature()" in html
    assert "const MB_SECTION_PATTERNS_BY_OP" in html
    assert "function _mbMissingSelectedSections(data, ops)" in html
    assert "const mbGenerationKey = `${S.circuitTemplateId || 'active'}:${opsSig}`;" in html
    assert "missingSections.length > 0" in html


def test_equipment_register_autogenerates_from_selected_circuit():
    html = (BACKEND / "MetalFlowPro_v3_1.html").read_text(encoding="utf-8")

    assert "const merGenerationKey = `${S.circuitTemplateId || 'active'}:${opsSig}`;" in html
    assert "S._merAutoGeneratedForTemplate !== merGenerationKey" in html
    assert "await api('POST', merAutoGenerateUrl());" in html


def test_root_html_forces_no_cache_for_production_updates():
    source = (BACKEND / "main.py").read_text(encoding="utf-8")
    html = (BACKEND / "MetalFlowPro_v3_1.html").read_text(encoding="utf-8")

    assert "no-store, no-cache, must-revalidate, max-age=0" in source
    assert "X-MetalFlow-Build" in source
    assert "APP_BUILD_ID" in source
    assert APP_BUILD_ID in html


def test_static_frontends_resolve_api_origin_to_backend_service():
    backend_html = (BACKEND / "MetalFlowPro_v3_1.html").read_text(encoding="utf-8")
    frontend_html = (REPO_ROOT / "frontend" / "public" / "index.html").read_text(encoding="utf-8")

    for html in (backend_html, frontend_html):
        assert "const METALFLOW_BACKEND_ORIGIN = 'https://metalflow-pro-production.up.railway.app';" in html
        assert "window.location.protocol === 'file:'" in html
        assert "window.location.hostname === 'metalflow-frontend-production.up.railway.app'" in html
        assert "return METALFLOW_BACKEND_ORIGIN;" in html

    assert "Impossible de joindre le serveur — vérifiez que le backend est accessible (${API_ORIGIN})" in backend_html
